// apps/web-solid/src/App.tsx
import { Component, createSignal, For } from "solid-js";
import { Avatar, Variant } from "@boringer-avatars/solid";
import {
  VariantSelector,
  SizeSelector,
  PaletteSelector,
  ShapeSelector,
  LightDarkToggle,
  LibraryLinks,
  exampleNames,
} from "@demo/solid";
import "./styles.css";

const App: Component = () => {
  const [variant, setVariant] = createSignal("beam");
  const [isSquare, setIsSquare] = createSignal(false);
  const [size, setSize] = createSignal("40px");
  const [colors, setColors] = createSignal([
    "#FFAD08",
    "#EDD75A",
    "#73B06F",
    "#0C8F8F",
    "#405059",
  ]);
  const [theme, setTheme] = createSignal("light");

  return (
    <>
      <div class={`content ${theme()}`}>
        <div class="row">
          <div class="row">
            <VariantSelector
              variant={variant()}
              onChange={(newVariant: Variant) => {
                setVariant(newVariant);
                console.log({ newVariant, variant: variant() });
              }}
            />
          </div>
          <PaletteSelector
            colors={colors()}
            onChange={(newColors: string[]) => {
              console.log({ newColors });
              setColors(newColors);
            }}
          />
          <div class="row">
            <div class="inner-row">
              <ShapeSelector
                shape={isSquare() ? "square" : "circle"}
                onChange={(newShape: string) => {
                  console.log({ newShape });
                  setIsSquare(newShape === "square");
                }}
              />
              <SizeSelector
                size={size()}
                onChange={(newSize: any) => {
                  console.log({ newSize });
                  setSize(newSize);
                }}
              />
              <LightDarkToggle
                theme={theme()}
                onChange={(newTheme: string) => {
                  console.log("new theme", theme);
                  setTheme(newTheme);
                }}
              />
            </div>
            <div class="inner-row">
              <LibraryLinks githubUrl="https://github.com/cmgriffing/boringer-avatars/blob/main/packages/lib-react" />
            </div>
          </div>
        </div>
        <div class="avatar-list">
          <For each={exampleNames}>
            {(name) => (
              <div class="avatar-list-item">
                <Avatar
                  test={variant() + "foo"}
                  title={false}
                  size={size()}
                  variant={variant()}
                  name={name}
                  square={isSquare()}
                  colors={colors()}
                />
                <div class="avatar-list-item-name">{name as string}</div>
              </div>
            )}
          </For>
        </div>
      </div>
    </>
  );
};

export default App;

// export default function Web() {
//   const [variant, setVariant] = useState("beam" as Variant);
//   const [isSquare, setIsSquare] = useState(false);
//   const [size, setSize] = useState("40px" as any);
//   const [colors, setColors] = useState([
//     "#FFAD08",
//     "#EDD75A",
//     "#73B06F",
//     "#0C8F8F",
//     "#405059",
//   ]);
//   const [theme, setTheme] = useState("light");

//   return (
//   );
// }

// apps/web-svelte/src/App.svelte
<script lang="ts">
  import { Avatar } from "@boringer-avatars/svelte/package";

  import {
    VariantSelector,
    SizeSelector,
    PaletteSelector,
    ShapeSelector,
    LightDarkToggle,
    LibraryLinks,
    exampleNames,
  } from "@demo/svelte/package";

  let variant = "beam";
  let isSquare = false;
  let size = "40px";
  let colors = ["#FFAD08", "#EDD75A", "#73B06F", "#0C8F8F", "#405059"];
  let theme = "light";
</script>

<main>
  <div class={`content ${theme}`}>
    <div class="row">
      <div class="row">
        <VariantSelector
          {variant}
          onChange={(newVariant) => {
            variant = newVariant;
          }}
        />
      </div>
      <PaletteSelector
        {colors}
        onChange={(newColors) => {
          console.log({ newColors });
          colors = newColors;
        }}
      />
      <div class="row">
        <div class="inner-row">
          <ShapeSelector
            shape={isSquare ? "square" : "circle"}
            onChange={(newShape) => {
              console.log({ newShape });
              isSquare = newShape === "square";
            }}
          />
          <SizeSelector
            {size}
            onChange={(newSize) => {
              size = newSize;
            }}
          />
          <LightDarkToggle
            {theme}
            onChange={(newTheme) => {
              theme = newTheme;
            }}
          />
        </div>
        <div class="inner-row">
          <LibraryLinks
            githubUrl="https://github.com/cmgriffing/boringer-avatars/blob/main/packages/lib-svelte"
          />
        </div>
      </div>
    </div>
    <div class="avatar-list">
      {#each exampleNames as name}
        <div class="avatar-list-item">
          <Avatar
            title={false}
            {size}
            {variant}
            {name}
            square={isSquare}
            {colors}
          />
          <div class="avatar-list-item-name">{name}</div>
        </div>
      {/each}
    </div>
  </div>
</main>
