// packages/lib-svelte/src/lib/avatar.svelte
<script>
  import { onMount } from "svelte";

  import { coerceVariant, defaultAvatarProps } from "./avatar.utils";
  import AvatarBauhaus from "./avatars/avatar-bauhaus.svelte";
  import AvatarBeam from "./avatars/avatar-beam.svelte";
  import AvatarMarble from "./avatars/avatar-marble.svelte";
  import AvatarPixel from "./avatars/avatar-pixel.svelte";
  import AvatarRing from "./avatars/avatar-ring.svelte";
  import AvatarSunset from "./avatars/avatar-sunset.svelte";

  export let variant;
  export let size;
  export let colors;
  export let name;
  export let square;
  export let title;

  let checkedVariant = "beam";
  let coercedProps = defaultAvatarProps;

  onMount(() => {
    checkedVariant = coerceVariant(variant) || "beam";
    coercedProps = { ...defaultAvatarProps, ...$$props };
  });

  function onUpdateFn_0() {
    checkedVariant = coerceVariant(variant) || "beam";
    coercedProps = { ...defaultAvatarProps, ...$$props };
  }
  $: onUpdateFn_0(...[variant, size, colors, name, square, title]);
</script>

{#if checkedVariant === `bauhaus`}
  <AvatarBauhaus
    colors={coercedProps.colors}
    name={coercedProps.name}
    square={coercedProps.square}
    title={coercedProps.title}
    size={coercedProps.size}
  />
{/if}

{#if checkedVariant === `beam`}
  <AvatarBeam
    colors={coercedProps.colors}
    name={coercedProps.name}
    square={coercedProps.square}
    title={coercedProps.title}
    size={coercedProps.size}
  />
{/if}

{#if checkedVariant === `marble`}
  <AvatarMarble
    colors={coercedProps.colors}
    name={coercedProps.name}
    square={coercedProps.square}
    title={coercedProps.title}
    size={coercedProps.size}
  />
{/if}

{#if checkedVariant === `pixel`}
  <AvatarPixel
    colors={coercedProps.colors}
    name={coercedProps.name}
    square={coercedProps.square}
    title={coercedProps.title}
    size={coercedProps.size}
  />
{/if}

{#if checkedVariant === `ring`}
  <AvatarRing
    colors={coercedProps.colors}
    name={coercedProps.name}
    square={coercedProps.square}
    title={coercedProps.title}
    size={coercedProps.size}
  />
{/if}

{#if checkedVariant === `sunset`}
  <AvatarSunset
    colors={coercedProps.colors}
    name={coercedProps.name}
    square={coercedProps.square}
    title={coercedProps.title}
    size={coercedProps.size}
  />
{/if}

// packages/lib-react/src/avatar.tsx
import * as React from "react";
import { useState, useEffect } from "react";
import type { Variant } from "./avatar.utils";
import { AvatarProps, coerceVariant, defaultAvatarProps } from "./avatar.utils";
import AvatarBauhaus from "./avatars/avatar-bauhaus";
import AvatarBeam from "./avatars/avatar-beam";
import AvatarMarble from "./avatars/avatar-marble";
import AvatarPixel from "./avatars/avatar-pixel";
import AvatarRing from "./avatars/avatar-ring";
import AvatarSunset from "./avatars/avatar-sunset";

export default function Avatar(props: Partial<AvatarProps>) {
  const [checkedVariant, setCheckedVariant] = useState(() => "beam");

  const [coercedProps, setCoercedProps] = useState(() => defaultAvatarProps);

  useEffect(() => {
    setCheckedVariant(coerceVariant(props.variant) || "beam");
    setCoercedProps({ ...defaultAvatarProps, ...props });
  }, []);

  useEffect(() => {
    setCheckedVariant(coerceVariant(props.variant) || "beam");
    setCoercedProps({ ...defaultAvatarProps, ...props });
  }, [props.variant]);

  return (
    <>
      {checkedVariant === `bauhaus` ? (
        <>
          <AvatarBauhaus
            colors={coercedProps.colors}
            name={coercedProps.name}
            square={coercedProps.square}
            title={coercedProps.title}
            size={coercedProps.size}
          />
        </>
      ) : null}

      {checkedVariant === `beam` ? (
        <>
          <AvatarBeam
            colors={coercedProps.colors}
            name={coercedProps.name}
            square={coercedProps.square}
            title={coercedProps.title}
            size={coercedProps.size}
          />
        </>
      ) : null}

      {checkedVariant === `marble` ? (
        <>
          <AvatarMarble
            colors={coercedProps.colors}
            name={coercedProps.name}
            square={coercedProps.square}
            title={coercedProps.title}
            size={coercedProps.size}
          />
        </>
      ) : null}

      {checkedVariant === `pixel` ? (
        <>
          <AvatarPixel
            colors={coercedProps.colors}
            name={coercedProps.name}
            square={coercedProps.square}
            title={coercedProps.title}
            size={coercedProps.size}
          />
        </>
      ) : null}

      {checkedVariant === `ring` ? (
        <>
          <AvatarRing
            colors={coercedProps.colors}
            name={coercedProps.name}
            square={coercedProps.square}
            title={coercedProps.title}
            size={coercedProps.size}
          />
        </>
      ) : null}

      {checkedVariant === `sunset` ? (
        <>
          <AvatarSunset
            colors={coercedProps.colors}
            name={coercedProps.name}
            square={coercedProps.square}
            title={coercedProps.title}
            size={coercedProps.size}
          />
        </>
      ) : null}
    </>
  );
}
