// apps/web-vue3/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { Avatar } from "@boringer-avatars/vue3";

import {
  VariantSelector,
  SizeSelector,
  PaletteSelector,
  ShapeSelector,
  LightDarkToggle,
  LibraryLinks,
  exampleNames,
} from "@demo/vue3";

const variant = ref("beam");
const isSquare = ref(false);
const size = ref("40px");
const colors = ref(["#FFAD08", "#EDD75A", "#73B06F", "#0C8F8F", "#405059"]);
const theme = ref("light");

const onVariantChange = (newVariant: any) => {
  console.log({ newVariant });
  variant.value = newVariant;
};

const onColorsChange = (newColors: string[]) => {
  console.log({
    newColors,
  });
  colors.value = newColors;
};

const onShapeChange = (newShape: string) => {
  console.log({ newShape });
  isSquare.value = newShape === "square";
};

const onSizeChange = (newSize: string) => {
  size.value = newSize;
};

const onThemeChange = (newTheme: string) => {
  theme.value = newTheme;
};
</script>

<template>
  <div :class="`content ${theme}`">
    <div class="row">
      <div class="row">
        <VariantSelector :variant="variant" :onChange="onVariantChange" />
      </div>
      <PaletteSelector :colors="colors" :onChange="onColorsChange" />
      <div class="row">
        <div class="inner-row">
          <ShapeSelector
            :shape="isSquare ? 'square' : 'circle'"
            :onChange="onShapeChange"
          />
          <SizeSelector :size="size" :onChange="onSizeChange" />
          <LightDarkToggle :theme="theme" :onChange="onThemeChange" />
        </div>
        <div class="inner-row">
          <LibraryLinks
            githubUrl="https://github.com/cmgriffing/boringer-avatars/packages/lib-svelte"
          />
        </div>
      </div>
    </div>
    <div class="avatar-list">
      <div class="avatar-list-item" v-for="name in exampleNames">
        <Avatar
          :title="false"
          :size="size"
          :variant="variant"
          :name="name"
          :square="isSquare"
          :colors="colors"
        />
        <div class="avatar-list-item-name">{{ name }}</div>
      </div>
    </div>
  </div>
</template>

// apps/web-angular/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import {
  AvatarSize,
  AvatarShape,
  AvatarVariant,
  Theme,
  exampleNames,
} from '@demo/angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
  title = 'web-angular';
  exampleNames = exampleNames;

  variant = AvatarVariant.Beam;
  shape = AvatarShape.Circle;
  size = AvatarSize.Medium;
  sizeNumber = parseInt(AvatarSize.Medium, 10);
  isSquare = false;
  colors = ['#FFAD08', '#EDD75A', '#73B06F', '#0C8F8F', '#405059'];
  theme = Theme.Light;

  onVariantChange(newVariant: any) {
    this.variant = newVariant;
  }

  onSizeChange(newSize: any) {
    this.size = newSize;
    this.sizeNumber = parseInt(newSize, 10);
  }

  onShapeChange(newShape: any) {
    this.shape = newShape;
    this.isSquare = newShape === AvatarShape.Square;
  }

  onColorsChange(newPalette: any) {
    this.colors = newPalette;
  }

  onThemeChange(newTheme: any) {
    this.theme = newTheme;
  }
}

<div class="content" [class.dark]="theme === 'dark'">
  <div class="row">
    <div class="row">
      <variant-selector
        [variant]="variant"
        (onChange)="onVariantChange($event)"
      ></variant-selector>
    </div>
    <palette-selector
      [colors]="colors"
      (onChange)="onColorsChange($event)"
    ></palette-selector>
    <div class="row">
      <div class="inner-row">
        <shape-selector
          [shape]="shape"
          (onChange)="onShapeChange($event)"
        ></shape-selector>
        <size-selector
          [size]="size"
          (onChange)="onSizeChange($event)"
        ></size-selector>
        <light-dark-toggle
          [theme]="theme"
          (onChange)="onThemeChange($event)"
        ></light-dark-toggle>
      </div>
      <div class="inner-row">
        <library-links
          githubUrl="https://github.com/cmgriffing/boringer-avatars/packages/lib-svelte"
        ></library-links>
      </div>
    </div>
  </div>
  <div class="avatar-list">
    <div class="avatar-list-item" *ngFor="let name of exampleNames">
      <avatar
        [title]="false"
        [size]="sizeNumber"
        [variant]="variant"
        [name]="name"
        [square]="isSquare"
        [colors]="colors"
      ></avatar>
      <div class="avatar-list-item-name">{{ name }}</div>
    </div>
  </div>
</div>
