// packages/lib-solid/src/avatar.jsx
import { Show } from "solid-js";

import { coerceVariant, defaultAvatarProps } from "./avatar.utils";
import AvatarBauhaus from "./avatars/avatar-bauhaus";
import AvatarBeam from "./avatars/avatar-beam";
import AvatarMarble from "./avatars/avatar-marble";
import AvatarPixel from "./avatars/avatar-pixel";
import AvatarRing from "./avatars/avatar-ring";
import AvatarSunset from "./avatars/avatar-sunset";

function Avatar(props) {
  return (
    <div>
      <Show when={props.variant === `bauhaus`}>
        <AvatarBauhaus
          colors={props.colors || defaultAvatarProps.colors}
          name={props.name || defaultAvatarProps.name}
          square={props.square || defaultAvatarProps.square}
          title={props.title || defaultAvatarProps.title}
          size={props.size || defaultAvatarProps.size}
        ></AvatarBauhaus>
      </Show>
      <Show when={props.variant === `beam`}>
        <AvatarBeam
          colors={props.colors || defaultAvatarProps.colors}
          name={props.name || defaultAvatarProps.name}
          square={props.square || defaultAvatarProps.square}
          title={props.title || defaultAvatarProps.title}
          size={props.size || defaultAvatarProps.size}
        ></AvatarBeam>
      </Show>
      <Show when={props.variant === `marble`}>
        <AvatarMarble
          colors={props.colors || defaultAvatarProps.colors}
          name={props.name || defaultAvatarProps.name}
          square={props.square || defaultAvatarProps.square}
          title={props.title || defaultAvatarProps.title}
          size={props.size || defaultAvatarProps.size}
        ></AvatarMarble>
      </Show>
      <Show when={props.variant === `pixel`}>
        <AvatarPixel
          colors={props.colors || defaultAvatarProps.colors}
          name={props.name || defaultAvatarProps.name}
          square={props.square || defaultAvatarProps.square}
          title={props.title || defaultAvatarProps.title}
          size={props.size || defaultAvatarProps.size}
        ></AvatarPixel>
      </Show>
      <Show when={props.variant === `ring`}>
        <AvatarRing
          colors={props.colors || defaultAvatarProps.colors}
          name={props.name || defaultAvatarProps.name}
          square={props.square || defaultAvatarProps.square}
          title={props.title || defaultAvatarProps.title}
          size={props.size || defaultAvatarProps.size}
        ></AvatarRing>
      </Show>
      <Show when={props.variant === `sunset`}>
        <AvatarSunset
          colors={props.colors || defaultAvatarProps.colors}
          name={props.name || defaultAvatarProps.name}
          square={props.square || defaultAvatarProps.square}
          title={props.title || defaultAvatarProps.title}
          size={props.size || defaultAvatarProps.size}
        ></AvatarSunset>
      </Show>
    </div>
  );
}

export default Avatar;

// packages/lib-vue2/src/avatar.vue
<template>
  <div>
    <template v-if="variant === `bauhaus`">
      <avatar-bauhaus
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-bauhaus>
    </template>

    <template v-if="variant === `beam`">
      <avatar-beam
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-beam>
    </template>

    <template v-if="variant === `marble`">
      <avatar-marble
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-marble>
    </template>

    <template v-if="variant === `pixel`">
      <avatar-pixel
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-pixel>
    </template>

    <template v-if="variant === `ring`">
      <avatar-ring
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-ring>
    </template>

    <template v-if="variant === `sunset`">
      <avatar-sunset
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-sunset>
    </template>
  </div>
</template>

<script lang="ts">
import type { AvatarProps } from "./avatar.utils";

import { coerceVariant, defaultAvatarProps } from "./avatar.utils";
import AvatarBauhaus from "./avatars/avatar-bauhaus.vue";
import AvatarBeam from "./avatars/avatar-beam.vue";
import AvatarMarble from "./avatars/avatar-marble.vue";
import AvatarPixel from "./avatars/avatar-pixel.vue";
import AvatarRing from "./avatars/avatar-ring.vue";
import AvatarSunset from "./avatars/avatar-sunset.vue";

export default {
  name: "avatar",
  components: {
    AvatarBauhaus: AvatarBauhaus,
    AvatarBeam: AvatarBeam,
    AvatarMarble: AvatarMarble,
    AvatarPixel: AvatarPixel,
    AvatarRing: AvatarRing,
    AvatarSunset: AvatarSunset,
  },
  props: ["variant", "colors", "name", "square", "title", "size"],

  data: () => ({ defaultAvatarProps }),
};
</script>
