// packages/lib-svelte/src/lib/avatar.svelte
<script>
  import { defaultAvatarProps } from "./avatar.utils";
  import AvatarBauhaus from "./avatars/avatar-bauhaus.svelte";
  import AvatarBeam from "./avatars/avatar-beam.svelte";
  import AvatarMarble from "./avatars/avatar-marble.svelte";
  import AvatarPixel from "./avatars/avatar-pixel.svelte";
  import AvatarRing from "./avatars/avatar-ring.svelte";
  import AvatarSunset from "./avatars/avatar-sunset.svelte";

  export let variant;
  export let colors;
  export let name;
  export let square;
  export let hasTitle;
  export let size;
</script>

<div>
  {#if variant === `bauhaus`}
    <AvatarBauhaus
      colors={colors || defaultAvatarProps.colors}
      name={name || defaultAvatarProps.name}
      square={square || defaultAvatarProps.square}
      hasTitle={hasTitle || defaultAvatarProps.hasTitle}
      size={size || defaultAvatarProps.size}
    />
  {/if}

  {#if variant === `beam`}
    <AvatarBeam
      colors={colors || defaultAvatarProps.colors}
      name={name || defaultAvatarProps.name}
      square={square || defaultAvatarProps.square}
      hasTitle={hasTitle || defaultAvatarProps.hasTitle}
      size={size || defaultAvatarProps.size}
    />
  {/if}

  {#if variant === `marble`}
    <AvatarMarble
      colors={colors || defaultAvatarProps.colors}
      name={name || defaultAvatarProps.name}
      square={square || defaultAvatarProps.square}
      hasTitle={hasTitle || defaultAvatarProps.hasTitle}
      size={size || defaultAvatarProps.size}
    />
  {/if}

  {#if variant === `pixel`}
    <AvatarPixel
      colors={colors || defaultAvatarProps.colors}
      name={name || defaultAvatarProps.name}
      square={square || defaultAvatarProps.square}
      hasTitle={hasTitle || defaultAvatarProps.hasTitle}
      size={size || defaultAvatarProps.size}
    />
  {/if}

  {#if variant === `ring`}
    <AvatarRing
      colors={colors || defaultAvatarProps.colors}
      name={name || defaultAvatarProps.name}
      square={square || defaultAvatarProps.square}
      hasTitle={hasTitle || defaultAvatarProps.hasTitle}
      size={size || defaultAvatarProps.size}
    />
  {/if}

  {#if variant === `sunset`}
    <AvatarSunset
      colors={colors || defaultAvatarProps.colors}
      name={name || defaultAvatarProps.name}
      square={square || defaultAvatarProps.square}
      hasTitle={hasTitle || defaultAvatarProps.hasTitle}
      size={size || defaultAvatarProps.size}
    />
  {/if}
</div>

// packages/lib-vue3/src/avatar.vue
<template>
  <div>
    <template v-if="variant === `bauhaus`">
      <avatar-bauhaus
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-bauhaus>
    </template>

    <template v-if="variant === `beam`">
      <avatar-beam
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-beam>
    </template>

    <template v-if="variant === `marble`">
      <avatar-marble
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-marble>
    </template>

    <template v-if="variant === `pixel`">
      <avatar-pixel
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-pixel>
    </template>

    <template v-if="variant === `ring`">
      <avatar-ring
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-ring>
    </template>

    <template v-if="variant === `sunset`">
      <avatar-sunset
        :colors="colors || defaultAvatarProps.colors"
        :name="name || defaultAvatarProps.name"
        :square="square || defaultAvatarProps.square"
        :title="title || defaultAvatarProps.title"
        :size="size || defaultAvatarProps.size"
      ></avatar-sunset>
    </template>
  </div>
</template>

<script>
import { defaultAvatarProps } from "./avatar.utils";
import AvatarBauhaus from "./avatars/avatar-bauhaus.vue";
import AvatarBeam from "./avatars/avatar-beam.vue";
import AvatarMarble from "./avatars/avatar-marble.vue";
import AvatarPixel from "./avatars/avatar-pixel.vue";
import AvatarRing from "./avatars/avatar-ring.vue";
import AvatarSunset from "./avatars/avatar-sunset.vue";

export default {
  name: "avatar",
  components: {
    AvatarBauhaus: AvatarBauhaus,
    AvatarBeam: AvatarBeam,
    AvatarMarble: AvatarMarble,
    AvatarPixel: AvatarPixel,
    AvatarRing: AvatarRing,
    AvatarSunset: AvatarSunset,
  },
  props: ["variant", "colors", "name", "square", "title", "size"],

  data: () => ({ defaultAvatarProps }),
};
</script>
