// packages/demo-react/src/components/variant-selector.tsx
import * as React from "react";
import { useState, useEffect } from "react";
import type { VariantSelectorProps } from "./variant-selector.utils";
import { coerceVariant, AvatarVariant, variants } from "../utils/common.utils";

export default function VariantSelector(props: any) {
  const [selectedVariant, setSelectedVariant] = useState(() => "beam");

  function handleChange(event) {
    const newVariant = event?.target?.value || AvatarVariant.Marble;
    setSelectedVariant(newVariant);
    props.onChange(newVariant);
  }

  function getLabelClass(variantOption) {
    return `radio-label ${variantOption === selectedVariant ? "selected" : ""}`;
  }

  function getInputId(variantOption) {
    return `radio-${variantOption}`;
  }

  useEffect(() => {
    setSelectedVariant(coerceVariant(props.variant) || "beam");
  }, []);

  useEffect(() => {
    setSelectedVariant(coerceVariant(props.variant) || "beam");
  }, [props.variant]);

  return (
    <div className="variant-selector widget-wrapper">
      {variants?.map((variantOption) => (
        <label
          className={getLabelClass(variantOption)}
          htmlFor={getInputId(variantOption)}
        >
          <input
            type="radio"
            className="radio-item sr-only"
            name="variant-option"
            id={getInputId(variantOption)}
            value={variantOption}
            onChange={(event) => handleChange(event)}
          />

          {variantOption}
        </label>
      ))}
    </div>
  );
}

// packages/demo-solid/src/components/variant-selector.tsx
import { For, onMount, on, createEffect, createSignal } from "solid-js";

import type { VariantSelectorProps } from "./variant-selector.utils";

import { coerceVariant, AvatarVariant, variants } from "../utils/common.utils";

function VariantSelector(props: any) {
  const [selectedVariant, setSelectedVariant] = createSignal("beam");

  function handleChange(event) {
    const newVariant = event?.target?.value || AvatarVariant.Marble;
    setSelectedVariant(newVariant);
    props.onChange(newVariant);
  }

  function getLabelClass(variantOption) {
    return `radio-label ${
      variantOption === selectedVariant() ? "selected" : ""
    }`;
  }

  function getInputId(variantOption) {
    return `radio-${variantOption}`;
  }

  onMount(() => {
    setSelectedVariant(coerceVariant(props.variant) || "beam");
  });

  function onUpdateFn_0() {
    setSelectedVariant(coerceVariant(props.variant) || "beam");
  }
  createEffect(on(() => [props.variant], onUpdateFn_0));

  return (
    <div class="variant-selector widget-wrapper">
      <For each={variants}>
        {(variantOption, _index) => {
          const index = _index();
          return (
            <label
              class={getLabelClass(variantOption)}
              htmlFor={getInputId(variantOption)}
            >
              <input
                class="radio-item sr-only"
                type="radio"
                name="variant-option"
                id={getInputId(variantOption)}
                value={variantOption}
                onInput={(event) => handleChange(event)}
              />
              {variantOption}
            </label>
          );
        }}
      </For>
    </div>
  );
}

export default VariantSelector;
