// packages/demo-react/src/components/light-dark-toggle.tsx
import * as React from "react";
import { useState, useEffect } from "react";
import { Theme } from "../utils/common.utils";
import { LightDarkToggleProps } from "./light-dark-toggle.utils";

export default function LightDarkToggle(props: any) {
  const [selectedTheme, setSelectedTheme] = useState(() => Theme.Light);

  function handleChange(event) {
    const newTheme = selectedTheme === Theme.Dark ? Theme.Light : Theme.Dark;
    setSelectedTheme(newTheme);
    props.onChange(newTheme);
  }

  useEffect(() => {
    setSelectedTheme(props.theme || Theme.Light);
  }, []);

  useEffect(() => {
    setSelectedTheme(props.theme || Theme.Light);
  }, [props.theme]);

  return (
    <div className="light-dark-toggle widget-wrapper">
      <label className="checkbox-label" htmlFor="theme-checkbox">
        <input
          id="theme-checkbox"
          type="checkbox"
          className="sr-only radio-item"
          name="theme-checkbox"
          onChange={(event) => {
            handleChange(event);
          }}
        />

        <svg width="20" height="20" fill="none">
          <circle
            cx="10"
            cy="10"
            r="9"
            stroke="currentColor"
            stroke-width="2"
          />

          <path d="M10 0a10 10 0 000 20V0z" fill="currentColor" />
        </svg>
      </label>
    </div>
  );
}

// packages/demo-svelte/src/lib/components/light-dark-toggle.svelte
<script>
  import { onMount } from "svelte";

  import { Theme } from "../utils/common.utils";

  export let onChange;
  export let theme;

  function handleChange(event) {
    const newTheme = selectedTheme === Theme.Dark ? Theme.Light : Theme.Dark;
    selectedTheme = newTheme;
    onChange(newTheme);
  }

  let selectedTheme = Theme.Light;

  onMount(() => {
    selectedTheme = theme || Theme.Light;
  });

  function onUpdateFn_0() {
    selectedTheme = theme || Theme.Light;
  }
  $: onUpdateFn_0(...[theme]);
</script>

<div class="light-dark-toggle widget-wrapper">
  <label class="checkbox-label" for="theme-checkbox">
    <input
      type="checkbox"
      class="sr-only radio-item"
      name="theme-checkbox"
      id={`theme-checkbox`}
      on:change={(event) => {
        handleChange(event);
      }}
    />
    <svg width="20" height="20" fill="none">
      <circle cx="10" cy="10" r="9" stroke="currentColor" stroke-width="2" />
      <path d="M10 0a10 10 0 000 20V0z" fill="currentColor" />
    </svg>
  </label>
</div>
